# 3 - Tipos e Conversão de tipos
O Numpy suporta uma variedade de tipos muito maior do que o Python.

Existem 5 tipos básicos numéricos
- Booleans (bool)
- Integers (int)
- Unsigned Intergers (uint)
- Floating Points (float)
- Complex

Complementarmente, a célula abaixo mostra um quadro comparativos com uma maior quantidade de tipos do Numpy.

In [ ]:
import numpy as np

Cria uma variavel x e nessa variavel ele passa o retorno de np.float32, que é um valor float32.

In [ ]:
x = np.float32(1.0)
x

1.0

Cria um array e define ele como do tipo inteiro

In [ ]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

Cria um array de tamanho 3 de 0 a 2 com o tipo unsigned int de 8 bits

In [ ]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

Cria uma array [1 2 3] do tipo float

In [ ]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

## Convertendo tipos de arrays

Para convertermos arrays Numpy, basta utilizarmos o método astype().

In [ ]:
z.astype(float)

Pode converter também utilizando np.type, como mostrado

In [ ]:
np.int8(z)


dtype('int8')

Para verificarmos o tipo de um array Numpy, basta verificarmos o seu atributo dtype.

In [ ]:
z.dtype

dtype('uint8')